version: "3"

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
        - C:\Users\bogda\OneDrive\Documente\GitHub\keycloak-workshop-stepup-mfa-biometrics\nginx\default.conf
        - C:\Users\bogda\OneDrive\Documente\GitHub\keycloak-workshop-stepup-mfa-biometrics\certs\localhost.csr
        - C:\Users\bogda\OneDrive\Documente\GitHub\keycloak-workshop-stepup-mfa-biometrics\certs\localhost.key
    ports:
        - "80:80"
        - "443:443"
    depends_on:
      - keycloak    